drop table PRODUCT;
drop table PRODUCT_DEFINITION;
drop table CATEGORY;
CREATE TABLE PRODUCT (ID integer PRIMARY KEY, PRODUCT_DEFINITION integer NOT NULL, QUANTITY integer, QUANTITY_UNIT text, PRICE real, PRICE_UNIT text, STATE integer NOT NULL);
CREATE TABLE PRODUCT_DEFINITION (ID integer PRIMARY KEY, CATEGORY text NOT NULL, NAME text NOT NULL);
CREATE TABLE CATEGORY (ID integer PRIMARY KEY, NAME text NOT NULL UNIQUE);